language: c
compiler:
- gcc

before-install:
- sudo apt-get update
install:
- sudo apt-get install build-essential libssl-dev flex bison
script: "./configure && make && make install"

notifications:
  template:
      - "%{repository_name} - %{commit}/%{commit_message} - %{author})"
      - "Build Status %{message}"
  irc: "ircs://irc.chatfreedom.us:6697#sIRCd"
